<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="7" ignored="0" total="16" passed="9">
  <reporter-output>
  </reporter-output>
  <suite name="Chrome" duration-ms="312492" started-at="2019-08-13T12:14:26Z" finished-at="2019-08-13T12:19:38Z">
    <groups>
    </groups>
    <test name="Chrome" duration-ms="312492" started-at="2019-08-13T12:14:26Z" finished-at="2019-08-13T12:19:38Z">
      <class name="Stepdef.Scifi_Register">
        <test-method status="PASS" signature="i_am_not_a_user_of_agate_on_Scifi_and_I_open_a_browser(java.lang.String)[pri:0, instance:Stepdef.Scifi_Register@6321e813]" name="i_am_not_a_user_of_agate_on_Scifi_and_I_open_a_browser" duration-ms="1549" started-at="2019-08-13T12:14:26Z" finished-at="2019-08-13T12:14:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- i_am_not_a_user_of_agate_on_Scifi_and_I_open_a_browser -->
        <test-method status="PASS" signature="i_navigate_to_a_premium_article_on_Scifi()[pri:1, instance:Stepdef.Scifi_Register@6321e813]" name="i_navigate_to_a_premium_article_on_Scifi" duration-ms="11740" started-at="2019-08-13T12:14:28Z" finished-at="2019-08-13T12:14:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- i_navigate_to_a_premium_article_on_Scifi -->
        <test-method status="PASS" signature="i_click_on_the_create_wallet_button_on_scifi()[pri:2, instance:Stepdef.Scifi_Register@6321e813]" name="i_click_on_the_create_wallet_button_on_scifi" duration-ms="19109" started-at="2019-08-13T12:14:39Z" finished-at="2019-08-13T12:14:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- i_click_on_the_create_wallet_button_on_scifi -->
        <test-method status="PASS" signature="i_verify_that_the_create_wallet_button_takes_me_to_the_reg_page_on_scifi()[pri:3, instance:Stepdef.Scifi_Register@6321e813]" name="i_verify_that_the_create_wallet_button_takes_me_to_the_reg_page_on_scifi" duration-ms="12035" started-at="2019-08-13T12:14:58Z" finished-at="2019-08-13T12:15:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- i_verify_that_the_create_wallet_button_takes_me_to_the_reg_page_on_scifi -->
        <test-method status="PASS" signature="i_enter_all_the_details_successfully_on_reg_page_on_scifi()[pri:4, instance:Stepdef.Scifi_Register@6321e813]" name="i_enter_all_the_details_successfully_on_reg_page_on_scifi" duration-ms="47288" started-at="2019-08-13T12:15:10Z" finished-at="2019-08-13T12:15:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- i_enter_all_the_details_successfully_on_reg_page_on_scifi -->
        <test-method status="FAIL" signature="i_am_registered_as_an_agate_user_on_scifi_successfully_and_I_am_shown_a_first_use_notice()[pri:5, instance:Stepdef.Scifi_Register@6321e813]" name="i_am_registered_as_an_agate_user_on_scifi_successfully_and_I_am_shown_a_first_use_notice" duration-ms="50038" started-at="2019-08-13T12:15:58Z" finished-at="2019-08-13T12:16:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<0.25> but was:<0.0>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<0.25> but was:<0.0>
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
at Stepdef.Scifi_Register.i_am_registered_as_an_agate_user_on_scifi_successfully_and_I_am_shown_a_first_use_notice(Scifi_Register.java:239)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- i_am_registered_as_an_agate_user_on_scifi_successfully_and_I_am_shown_a_first_use_notice -->
      </class> <!-- Stepdef.Scifi_Register -->
      <class name="Stepdef.Scifi_Transaction$scifi_Transaction">
        <test-method status="PASS" signature="i_am_a_registered_Agate_User_and_I_login_in_to_scifi(java.lang.String)[pri:6, instance:Stepdef.Scifi_Transaction$scifi_Transaction@79be0360]" name="i_am_a_registered_Agate_User_and_I_login_in_to_scifi" duration-ms="48618" started-at="2019-08-13T12:16:48Z" finished-at="2019-08-13T12:17:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- i_am_a_registered_Agate_User_and_I_login_in_to_scifi -->
        <test-method status="PASS" signature="i_read_a_premium_article_on_scifi()[pri:7, instance:Stepdef.Scifi_Transaction$scifi_Transaction@79be0360]" name="i_read_a_premium_article_on_scifi" duration-ms="12497" started-at="2019-08-13T12:17:36Z" finished-at="2019-08-13T12:17:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- i_read_a_premium_article_on_scifi -->
        <test-method status="PASS" signature="the_wallet_balance_and_free_point_are_deducted_by_x_amount_on_scifi_wallet()[pri:8, instance:Stepdef.Scifi_Transaction$scifi_Transaction@79be0360]" name="the_wallet_balance_and_free_point_are_deducted_by_x_amount_on_scifi_wallet" duration-ms="10144" started-at="2019-08-13T12:17:49Z" finished-at="2019-08-13T12:17:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- the_wallet_balance_and_free_point_are_deducted_by_x_amount_on_scifi_wallet -->
        <test-method status="FAIL" signature="the_popbitch_wallet_balance_is_updated_same_as_scifi_and_free_point_remains_uneffected()[pri:9, instance:Stepdef.Scifi_Transaction$scifi_Transaction@79be0360]" name="the_popbitch_wallet_balance_is_updated_same_as_scifi_and_free_point_remains_uneffected" duration-ms="17951" started-at="2019-08-13T12:17:59Z" finished-at="2019-08-13T12:18:17Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<50> but was:<until free>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<50> but was:<until free>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
at Stepdef.Scifi_Transaction$scifi_Transaction.the_popbitch_wallet_balance_is_updated_same_as_scifi_and_free_point_remains_uneffected(Scifi_Transaction.java:245)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- the_popbitch_wallet_balance_is_updated_same_as_scifi_and_free_point_remains_uneffected -->
        <test-method status="PASS" signature="Reactions_wallet_balance_is_updated_and_free_point_remains_uneffected_as_on_scifi()[pri:10, instance:Stepdef.Scifi_Transaction$scifi_Transaction@79be0360]" name="Reactions_wallet_balance_is_updated_and_free_point_remains_uneffected_as_on_scifi" duration-ms="14230" started-at="2019-08-13T12:18:17Z" finished-at="2019-08-13T12:18:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Reactions_wallet_balance_is_updated_and_free_point_remains_uneffected_as_on_scifi -->
        <test-method status="FAIL" signature="cricketer_wallet_balance_is_updated_and_free_point_remains_unaffected_by_scifi()[pri:11, instance:Stepdef.Scifi_Transaction$scifi_Transaction@79be0360]" name="cricketer_wallet_balance_is_updated_and_free_point_remains_unaffected_by_scifi" duration-ms="10114" started-at="2019-08-13T12:18:31Z" finished-at="2019-08-13T12:18:41Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<9.8> but was:<9.75>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<9.8> but was:<9.75>
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
at Stepdef.Scifi_Transaction$scifi_Transaction.cricketer_wallet_balance_is_updated_and_free_point_remains_unaffected_by_scifi(Scifi_Transaction.java:353)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cricketer_wallet_balance_is_updated_and_free_point_remains_unaffected_by_scifi -->
        <test-method status="FAIL" signature="cornwall_wallet_balance_remains_and_is_uneffected_according_to_scifi()[pri:12, instance:Stepdef.Scifi_Transaction$scifi_Transaction@79be0360]" name="cornwall_wallet_balance_remains_and_is_uneffected_according_to_scifi" duration-ms="10389" started-at="2019-08-13T12:18:41Z" finished-at="2019-08-13T12:18:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<9.8> but was:<9.75>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<9.8> but was:<9.75>
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
at Stepdef.Scifi_Transaction$scifi_Transaction.cornwall_wallet_balance_remains_and_is_uneffected_according_to_scifi(Scifi_Transaction.java:418)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cornwall_wallet_balance_remains_and_is_uneffected_according_to_scifi -->
        <test-method status="FAIL" signature="maidenhead_wallet_balance_remains_and_is_uneffected_by_scifi()[pri:13, instance:Stepdef.Scifi_Transaction$scifi_Transaction@79be0360]" name="maidenhead_wallet_balance_remains_and_is_uneffected_by_scifi" duration-ms="13970" started-at="2019-08-13T12:18:52Z" finished-at="2019-08-13T12:19:06Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<9.8> but was:<9.75>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<9.8> but was:<9.75>
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
at Stepdef.Scifi_Transaction$scifi_Transaction.maidenhead_wallet_balance_remains_and_is_uneffected_by_scifi(Scifi_Transaction.java:483)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- maidenhead_wallet_balance_remains_and_is_uneffected_by_scifi -->
        <test-method status="FAIL" signature="slough_wallet_balance_remains_and_is_uneffected_by_scifi()[pri:14, instance:Stepdef.Scifi_Transaction$scifi_Transaction@79be0360]" name="slough_wallet_balance_remains_and_is_uneffected_by_scifi" duration-ms="13319" started-at="2019-08-13T12:19:06Z" finished-at="2019-08-13T12:19:19Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<9.8> but was:<9.75>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<9.8> but was:<9.75>
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
at Stepdef.Scifi_Transaction$scifi_Transaction.slough_wallet_balance_remains_and_is_uneffected_by_scifi(Scifi_Transaction.java:543)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- slough_wallet_balance_remains_and_is_uneffected_by_scifi -->
        <test-method status="FAIL" signature="windsor_wallet_balance_remains_and_is_uneffected_by_scifi()[pri:15, instance:Stepdef.Scifi_Transaction$scifi_Transaction@79be0360]" name="windsor_wallet_balance_remains_and_is_uneffected_by_scifi" duration-ms="19443" started-at="2019-08-13T12:19:19Z" finished-at="2019-08-13T12:19:38Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<9.8> but was:<9.75>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<9.8> but was:<9.75>
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
at Stepdef.Scifi_Transaction$scifi_Transaction.windsor_wallet_balance_remains_and_is_uneffected_by_scifi(Scifi_Transaction.java:603)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- windsor_wallet_balance_remains_and_is_uneffected_by_scifi -->
      </class> <!-- Stepdef.Scifi_Transaction$scifi_Transaction -->
    </test> <!-- Chrome -->
  </suite> <!-- Chrome -->
</testng-results>
